name: tests

variables:
  - group: unittest-samples
  - name: self_location
    value: "self_location"
  - name: full_self_location
    value: "$(Agent.BuildDirectory)/$(self_location)"
  - name: samples_location
    value: "samples_location"
  - name: full_samples_location
    value: "$(Agent.BuildDirectory)/$(samples_location)"

resources:
  repositories:
  - repository: unittest-samples
    type: github
    name: $(unittest_samples_repository)
    ref: main
    endpoint: github-repo-sa
    trigger: none

trigger: ["*"]
pr: ["*"]

pool:
  vmImage: "ubuntu-20.04"

jobs:
  - job: run_test
    strategy:
      matrix:
        Python3_9:
          python.version: "3.9"
        #Python3_10:
        #  python.version: "3.10"
        #Python3_11:
        #  python.version: "3.11"

    timeoutInMinutes: 10

    steps:
      - task: UsePythonVersion@0
        displayName: Set python version
        inputs:
          versionSpec: "$(python.version)"
      - checkout: self
        fetchDepth: 1
        path: $(self_location)
      - checkout: unittest-samples
        fetchDepth: 1
        path: $(samples_location)
      - script: |
          set -x # echo on
          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          sudo apt-get update
          sudo apt-get install -y libfuzzy-dev libfuzzy2 wget apt-transport-https software-properties-common
          if [[ -f "$(pwd)/pkglist.txt" ]]; then
            grep -vE '^#' "$(pwd)/pkglist.txt" | xargs sudo apt install -y
          fi
          # Performing ViperMonkey-specific setup
          export pypy=pypy2.7-v7.3.3
          # Install pypy
          sudo apt-get update && sudo apt-get install -y wget bzip2 build-essential && rm -rf /var/lib/apt/lists/*
          sudo wget -O /tmp/${pypy}-linux64.tar.bz2 https://downloads.python.org/pypy/${pypy}-linux64.tar.bz2
          sudo tar -xvf /tmp/${pypy}-linux64.tar.bz2 -C /opt
          sudo ln -s /opt/${pypy}-linux64/bin/pypy /usr/local/bin/pypy

          # Install packages
          sudo pypy -m ensurepip
          sudo pypy -m pip install --no-cache-dir -U pip

          sudo pypy -m pip install colorlog==5.0.0 regex==2021.11.10
          # Temp replacement until upstream merges changes
          sudo pypy -m pip install --no-cache-dir -U https://github.com/cccs-jh/ViperMonkey/archive/kirk.zip

          # See https://github.com/yaml/pyyaml/issues/601
          sudo pypy -m pip install wheel
          sudo pypy -m pip install "Cython<3.0" pyyaml --no-build-isolation
          sudo pypy -m pip install --no-cache-dir assemblyline_v4_p2compat pyparsing==2.2.0

          sudo rm -rf /var/lib/apt/lists/*
          sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir assemblyline assemblyline_v4_service
          [ -f $(pwd)/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/requirements.txt
          [ -f $(pwd)/tests/requirements.txt ] && sudo env "PATH=$PATH" python -m pip install -U --no-cache-dir -r $(pwd)/tests/requirements.txt
          sudo rm -rf /tmp/* /var/lib/apt/lists/* ~/.cache/pip
        workingDirectory: $(full_self_location)
        displayName: Setup environment
      - script: |
          [ ! -d "$(pwd)/tests" ] && echo "No tests found" && exit
          export REPO_NAME=${BUILD_REPOSITORY_NAME##*/}
          python -m pytest -p no:cacheprovider --durations=10 -rsx -xsvvv --disable-warnings
        workingDirectory: $(full_self_location)
        displayName: Test
